name = "open-bookmarks-web"
compatibility_date = "2024-01-01"

[env.production]
name = "open-bookmarks-web"
# vars = { VITE_SERVER_URL = "https://open-bookmarks-api.alexandrecoyras.workers.dev" }

[env.staging]
name = "open-bookmarks-web-staging" 
# vars = { VITE_SERVER_URL = "https://open-bookmarks-api-staging.alexandrecoyras.workers.dev" }

[env.development]
name = "open-bookmarks-web-dev"
# vars = { VITE_SERVER_URL = "http://localhost:3000" }